/* ================================================================
   Product data, generated from the shop's inventory sheet.
   price is left blank until real selling prices are set --
   the site shows a bilingual 'Contact for price' automatically
   whenever price is empty. Edit items/prices below directly.
   ================================================================ */
const PRODUCT_CATEGORIES = [
  {
    id: "bell",
    en: "Bells & Ghanti",
    ne: "घन्टी / घन्टा",
    icon: "🔔",
    items: [
      { en: "Temple Bell (Premium)", ne: "मन्दिर घन्टी (राम्रो)", price: "" },
      { en: "Temple Hanging Bell", ne: "बयेल घन्टी", price: "" },
      { en: "Brass Puja Handheld Bell", ne: "पित्तलको पूजा हाते घन्टी", price: "Rs. 3,000/KG", img: "images/products/brass-hate-ghanti.jpg" },
      { en: "Vastu Small Bell", ne: "बास्तु सानो घन्टी", price: "" },
      { en: "Puja Bell", ne: "पूजा घन्टी", price: "" },
      { en: "Ritual Drum (Damaru)", ne: "डमरु", price: "" },
      { en: "Brass Handheld Bell", ne: "पित्तलको हाते घन्टी", price: "" },
    ]
  },
  {
    id: "murti",
    en: "Idols & Murti",
    ne: "मूर्ति तथा शिवलिंग",
    icon: "🛕",
    items: [
      { en: "Radha-Krishna Idol (Large)", ne: "राधाकृष्ण मूर्ति (ठुलो)", price: "" },
      { en: "Radha-Krishna Idol (Small)", ne: "राधाकृष्ण मूर्ति (सानो)", price: "" },
      { en: "Krishna Swing (Jhula)", ne: "कृष्णा झुल्ला पिङ", price: "" },
      { en: "Ganesh Laxmi Idol", ne: "गणेश लक्ष्मी मूर्ति", price: "" },
      { en: "Cast-metal Bronze Idol", ne: "ढलौट - कास को मूर्ति", price: "" },
      { en: "Shivalinga", ne: "शिवलिंग", price: "" },
      { en: "Copper Shiva Base (Jaladhari)", ne: "तामाको जलधारी", price: "" },
      { en: "Brass Shiva Base (Jaladhari)", ne: "पित्तलको जलधारी", price: "" },
      { en: "Conch Shell (Shankha) Stand", ne: "सङ्ख स्टेन्ड", price: "" },
      { en: "Vastu Deity Yantra", ne: "वस्तु देवता यन्त्रम", price: "" },
      { en: "Water Pot (Kamandalu)", ne: "कमण्डलु", price: "" },
      { en: "Brass Serpent Idol (Naga)", ne: "पित्तलको नाग", price: "" },
      { en: "Conch Shell (Shankha)", ne: "सङ्ख", price: "" },
      { en: "Brass Idol", ne: "पित्तलको मूर्ति", price: "" },
      { en: "Brass Serpent Idol (Naga)", ne: "पित्तलको नाग", price: "" },
      { en: "Brass Om Symbol", ne: "पित्तलको ओम", price: "" },
      { en: "Brass Serpent-Shaped Aarti Lamp", ne: "पित्तलको नागीन आरती", price: "" },
      { en: "Shivalinga Shiva Base (Jaladhari) (EEK)", ne: "शिवलिंग जलधारी (EEK)", price: "" },
    ]
  },
  {
    id: "diya",
    en: "Diya & Lamps",
    ne: "दीयो / बत्ती",
    icon: "🪔",
    items: [
      { en: "Cooking Pot (Tauli) Oil Lamp (Diya)", ne: "ताउली दियो", price: "" },
      { en: "Brass Five-Wick Aarti Lamp", ne: "पित्तलको पंच-आरती", price: "" },
      { en: "Copper Oil Lamp (Diya) (Pressed Plain)", ne: "तामाको दियो (प्रेस -प्लेन)", price: "" },
      { en: "Standing Oil Lamp (Diya)", ne: "ठाडो दियो", price: "" },
      { en: "Brass Standing Lotus Lamp", ne: "पित्तलको ठाडो कमल बत्ति", price: "" },
      { en: "Copper Oil Lamp (Diya)", ne: "तामाको दियो", price: "" },
      { en: "Buddha Oil Lamp (Diya)", ne: "बुद्ध दियो", price: "" },
      { en: "Brass Single-Wick Aarti Lamp", ne: "पित्तलको एक्मुखे आरती", price: "" },
      { en: "Copper Ritual Oil Lamp (Diya)", ne: "तामाको पिठुवा दियो", price: "" },
      { en: "Brass Standing Oil Lamp (Diya)", ne: "पित्तलको ठाडो दियो", price: "" },
      { en: "Copper Ritual Oil Lamp (Diya)", ne: "तामाको पिटुवा दियो", price: "" },
      { en: "Brass Aarti Lamp (Single-Wick)", ne: "पित्तलको आरती (एकमुखे)", price: "" },
      { en: "Bronze Five-Wick Aarti Lamp", ne: "कासको पंचआरती", price: "" },
      { en: "Copper Footed Oil Lamp (Diya)", ne: "तामाको खुट्टे दियो", price: "" },
      { en: "Brass Standing Lamp", ne: "पित्तलको ठाडो बत्ति", price: "" },
      { en: "Brass Buddha Oil Lamp (Diya)", ne: "पित्तलको बुद्ध दियो", price: "" },
      { en: "Copper Small Oil Lamp (Diya)", ne: "तामाको सानो दियो", price: "" },
      { en: "Copper Light Oil Lamp (Diya)", ne: "तामाको हल्का दियो", price: "" },
      { en: "Copper Footed Oil Lamp (Diya)", ne: "तामाको खुट्टे दियो", price: "" },
      { en: "Brass Ritual Incense Burner", ne: "पित्तलको पिटुवा धूपौरो", price: "" },
      { en: "Brass Plain Incense Burner", ne: "पित्तलको सादा धूपौरो", price: "" },
      { en: "Cotton Wicks", ne: "फुलबत्ति", price: "" },
    ]
  },
  {
    id: "kalash",
    en: "Kalash, Lota & Jugs",
    ne: "कलश / गाग्री / करुवा",
    icon: "🏺",
    items: [
      { en: "Bronze Water Jug (Karuwa)", ne: "कासको करुवा", price: "" },
      { en: "Brass Ritual Vessel (Panas)", ne: "पित्तलको पानस", price: "" },
      { en: "Copper Water Pot (Gagri)", ne: "तामाको गाग्री", price: "" },
      { en: "Copper Kalash Pot (Ghalcha / Gagri)", ne: "तामाको घल्चा कलश (गाग्री)", price: "" },
      { en: "Copper Engraved Water Jug (Karuwa)", ne: "तामा बुट्टे करुवा", price: "" },
      { en: "Copper Kalash (Pot)", ne: "तामाको कलश", price: "" },
      { en: "Copper Water Pot (Ghalcha)", ne: "तामाको घल्चा", price: "" },
      { en: "Brass Water Pot (Ghalcha)", ne: "पित्तलको घल्चा", price: "" },
      { en: "Copper Kalash (Pot)", ne: "तामाको कलश", price: "" },
      { en: "Copper Kalash (Pot)", ne: "तामाको कलश", price: "" },
      { en: "Copper Kalash (Pot) & Plate (Thali) (Complete Set)", ne: "तामाको कलश र थाली (सबै)", price: "" },
      { en: "Bronze Vessel", ne: "कासको भाडा", price: "" },
      { en: "Copper Water Jug (Karuwa) (Plain)", ne: "तामाको करुवा (सादा)", price: "" },
      { en: "Copper Jug", ne: "तामाको जग", price: "" },
      { en: "Momo Cooking Pot", ne: "मोमो पकाउने भाडो", price: "" },
      { en: "Copper Light Kalash (Pot) (Small)", ne: "तामाको हल्का कलश (सानो)", price: "" },
      { en: "Bronze Puja Water Jug (Karuwa) (Small)", ne: "कासको पूजा करुवा (सानो)", price: "" },
      { en: "Copper Kalash (Pot) Round Tray (Aari)", ne: "तामाको कलश आरी", price: "" },
    ]
  },
  {
    id: "bowl",
    en: "Bowls & Containers",
    ne: "कचौरा / बाटा",
    icon: "🥣",
    items: [
      { en: "Ceramic Bowl (Bowl)", ne: "सेरामिक बवोल (कचौडा)", price: "" },
      { en: "Brass Bowl (Kopra)", ne: "पित्तलको कोप्रा", price: "" },
      { en: "Bronze Footed Bowl", ne: "कासको खुट्टे कचौरा", price: "" },
      { en: "Bell-metal Bowl", ne: "चरेशको कचौरा", price: "" },
      { en: "Bronze Bowl", ne: "कासको कचौरा", price: "" },
      { en: "Steel Bowl (Small)", ne: "स्टीलको कचौरा (सानो)", price: "" },
      { en: "Steel Bowl (Large)", ne: "स्टीलको कचौरा (ठुलो)", price: "" },
      { en: "Steel Container (Small)", ne: "स्टीलको बाटा (सानो)", price: "" },
      { en: "Steel Container (Large)", ne: "स्टीलको बाटा (ठुलो)", price: "" },
      { en: "Brass Footed Bowl", ne: "पित्तलको खुट्टे कचौरा", price: "" },
      { en: "Brass Bowl (Large)", ne: "पित्तलको कचौरा (ठुलो)", price: "" },
      { en: "Brass Bowl (Large)", ne: "पित्तलको कचौरा (ठुलो)", price: "" },
      { en: "Bronze Bowl (Small)", ne: "कासको कचौरा (सानो)", price: "" },
      { en: "Bronze Footed Bowl (Small)", ne: "कासको खुट्टे कचौरा (सानो)", price: "" },
      { en: "Brass Footed Bowl", ne: "पित्तलको खुट्टे कचौरा", price: "" },
      { en: "Bronze Bowl", ne: "कासको कचौरा", price: "" },
    ]
  },
  {
    id: "glass",
    en: "Glasses",
    ne: "गिलास",
    icon: "🥛",
    items: [
      { en: "Silver-Plated (Polished) Glass", ne: "चादीको (पोलिश) गिलास", price: "" },
      { en: "Bronze Glass", ne: "कासको गिलास", price: "" },
      { en: "Brass Glass", ne: "पित्तलको गिलास", price: "" },
      { en: "Steel Glass", ne: "स्टीलको गिलास", price: "" },
      { en: "Brass Glass", ne: "पित्तलको गिलास", price: "" },
    ]
  },
  {
    id: "disposable",
    en: "Disposables & Party Items",
    ne: "पेपर प्लेट / वाइन ग्लास",
    icon: "🥤",
    items: [
      { en: "Paper Plate (5 No.)", ne: "पेपर प्लेट (५ नम्बर", price: "" },
      { en: "Paper Plate (6 No.)", ne: "पेपर प्लेट (६ नम्बर)", price: "" },
      { en: "Paper Plate (7 No.)", ne: "पेपर प्लेट (७ नम्बर)", price: "" },
      { en: "Paper Plate (8 No.)", ne: "पेपर प्लेट (८ नम्बर)", price: "" },
      { en: "Paper Plate (9 No.)", ne: "पेपर प्लेट (९ नम्बर)", price: "" },
      { en: "Paper Plate (10 No.)", ne: "पेपर प्लेट (१० नम्बर)", price: "" },
      { en: "Paper Plate (12 No.)", ne: "पेपर प्लेट (१२ नम्बर )", price: "" },
      { en: "Wine Glass (Large)", ne: "वाइन ग्लास (ठुलो)", price: "" },
      { en: "Wine Glass (Small)", ne: "वाइन ग्लास (सानो)", price: "" },
    ]
  },
  {
    id: "thali",
    en: "Thali, Plates & Cooking Pots",
    ne: "थाली / ताउली / भाँडा",
    icon: "🍽️",
    items: [
      { en: "Copper Large Rice-Cooking Pot (Tauli)", ne: "भात पकाउने ठुलो ताउली (तामाको)", price: "" },
      { en: "Copper Small Rice-Cooking Pot (Tauli)", ne: "भात पकाउने सानो ताउली (तामाको)", price: "" },
      { en: "Brass Rice-Cooking Pot (Tauli)", ne: "भात पकाउने ताउली (पित्तलको)", price: "" },
      { en: "Cooking Pot (Kasaudi) (Cast-metal)", ne: "कसौडी (ढलौट)", price: "" },
      { en: "Ceramic Plate (Premium)", ne: "सेरामिक प्लेट (राम्रो)", price: "" },
      { en: "Ceramic Plate (Standard)", ne: "सेरामिक प्लेट (नर्मल)", price: "" },
      { en: "Ceramic Plate (Small)", ne: "सेरामिक प्लेट (सानो)", price: "" },
      { en: "Copper Eight-Compartment Plate (Ashtathali) (IC)", ne: "तामाको अस्टथाली (IC)", price: "" },
      { en: "Brass Eight-Compartment Plate (Ashtathali)", ne: "पित्तलको अस्टथाली(", price: "" },
      { en: "Copper Moon-Shaped Ritual Plate (Thali)", ne: "तामाको चन्द्रमा पिठुवा थाली", price: "" },
      { en: "Copper Betel Plate (Thali)", ne: "तामाको बिट थाली", price: "" },
      { en: "Brass Ritual Round Tray (Aari)", ne: "पित्तलको पिठुवा आरी", price: "" },
      { en: "Copper Tika Plate (Thali)", ne: "तामाको टिका थाली", price: "" },
      { en: "Brass (Tray)", ne: "पित्तलको (TRAY)", price: "" },
      { en: "Copper Four-Sided Tika Plate (Thali)", ne: "तामाको चारपाटे टिका थाली", price: "" },
      { en: "Brass Four-Sided Plate (Thali)", ne: "पित्तलको चारपाटे थाली", price: "" },
      { en: "Copper Ritual Round Tray (Aari)", ne: "तामाको पिठुवा आरी", price: "" },
      { en: "Steel Tika Plate (Thali)", ne: "स्टीलको टिका थाली", price: "" },
      { en: "Steel (Tray)", ne: "स्टीलको (TRAY)", price: "" },
      { en: "Brass Wok (Karahi)", ne: "पित्तलको कराई", price: "" },
      { en: "Copper Cooking Pot (Tauli) Small Pot (Small)", ne: "तामाको ताउली मुन्द्रे (सानो)", price: "" },
      { en: "Rice Pot (Odani) (Small)", ne: "ओदानी (सानो)", price: "" },
      { en: "Rice Pot (Odani) (Large)", ne: "ओदानी (ठुलो)", price: "" },
      { en: "Plastic (Tray)", ne: "प्लास्टिकको (TRAY)", price: "" },
      { en: "Brass Ritual Vessel (Panchapatra)", ne: "पित्तलको पन्चपात्र", price: "" },
      { en: "Ritual Engraved Cooking Pot (Tauli)", ne: "पिठुवा बुट्टे ताउली", price: "" },
      { en: "Engraved Cooking Pot (Tauli) (Small)", ne: "बुट्टे ताउली (सानो)", price: "" },
      { en: "Cooking Pot (Tauli) (Pressed) Plain", ne: "ताउली (प्रेस) प्लेन", price: "" },
      { en: "Moon/Sun-Shaped Plate (Thali)", ne: "चन्द्रमा थालि (सुर्य थाली)", price: "" },
      { en: "Brass Ritual Vessel (Purnapatra) Round Tray (Aari)", ne: "पित्तलको पुर्णपात्र आरी", price: "" },
      { en: "Copper Ritual Vessel (Purnapatra) Round Tray (Aari)", ne: "तामाको पूर्णपात्र आरी", price: "" },
      { en: "Copper Ganesh Plate (Thali)", ne: "तामाको गणेश थालि", price: "" },
      { en: "Brass Cooking Pot (Dekchi)", ne: "पित्तलको देक्ची", price: "" },
      { en: "Brass Plate (Thali)", ne: "पित्तलको थाली", price: "" },
      { en: "Brass Seven-Item Plate Set (Saptathali)", ne: "पित्तलको सप्तथाली", price: "" },
      { en: "Steel Seven-Item Plate Set (Saptathali)", ne: "स्टीलको सप्तथाली", price: "" },
      { en: "Bell-metal Plate (Thal)", ne: "चरेसको थाल", price: "" },
      { en: "Brass Plate (Thal)", ne: "पित्तलको थाल", price: "" },
      { en: "Bell-metal Black Polished Plate (Thal)", ne: "चरेशको कालो पोलिश थाल", price: "" },
      { en: "Steel Plate (Small)", ne: "स्टीलको प्लेट (सानो)", price: "" },
      { en: "Steel Cooking Pot (Dekchi)", ne: "स्टीलको डेक्ची", price: "" },
      { en: "Brass Ritual Container", ne: "पित्तलको पन्यु", price: "" },
      { en: "Bronze Ritual Container", ne: "कासको पन्यु", price: "" },
      { en: "Copper Ritual Vessel (Panchapatra)", ne: "तामाको पंचपात्र", price: "" },
      { en: "Copper Plate (Thali) & Round Tray (Aari) (Complete Set)", ne: "तामाको थाली र आरी (सबै)", price: "" },
      { en: "Brass (Tray) & Plate (Thali) (Complete Set)", ne: "पित्तलको (TRAY) र थाली (सबै)", price: "" },
      { en: "Brass Ritual Round Tray (Aari)", ne: "पित्तलको पिटुवा आरी", price: "" },
      { en: "Copper Engraved Cooking Pot (Tauli)", ne: "तामाको बुट्टे ताउली", price: "" },
      { en: "Copper Ritual Plate (Thali)", ne: "तामाको पिटुवा थाली", price: "" },
      { en: "Copper Cooking Pot (Tauli) Large (3+2) PCS", ne: "तामाको ताउली ठुलो (3+2) pcs", price: "" },
      { en: "Copper Cooking Pot (Tauli) 8 INCH (1300)", ne: "तामाको ताउली 8 INCH (1300)", price: "" },
      { en: "Copper Cooking Pot (Tauli) 17 INCH (2380)", ne: "तामाको ताउली 17 INCH (2380)", price: "" },
      { en: "Copper Cooking Pot (Tauli) 11 INCH (1550)", ne: "तामाको ताउली 11 INCH (1550)", price: "" },
      { en: "Plastic Compartment Plate (Thal)", ne: "प्लास्टिकको खन्डे थाल", price: "" },
      { en: "Plastic Plain Plate (Thal)", ne: "प्लास्टिकको प्लेन थाल", price: "" },
    ]
  },
  {
    id: "incense",
    en: "Incense & Dhoop Stands",
    ne: "धुप स्टेन्ड / अगरबत्ती",
    icon: "🕯️",
    items: [
      { en: "Rolled Incense Stand", ne: "बाटेको धुप स्टेन्ड", price: "" },
      { en: "Brass Incense Stand", ne: "पित्तलको धुप स्टेन्ड", price: "" },
      { en: "Brass Incense Stick Holder (RRK)", ne: "पित्तलको अगरबत्ती दानी (RRK)", price: "" },
      { en: "Camphor Shiva Shakti", ne: "कपुर शिव शक्ति", price: "" },
      { en: "Brass Incense Stand", ne: "पितलको धुप स्टएण्ड", price: "" },
      { en: "Rolled Incense", ne: "बाटेको धूप", price: "" },
    ]
  },
  {
    id: "cloth",
    en: "Cloth, Thread & Ceremonial Items",
    ne: "कपडा / धागो / खादा",
    icon: "🧵",
    items: [
      { en: "Plain Cloth", ne: "कोरा कपडा", price: "" },
      { en: "Nepali (Handmade) Paper", ne: "नेपाली कागज", price: "" },
      { en: "Ceremonial Scarf (Khada) Cloth", ne: "खादा कपडा", price: "" },
      { en: "Poplin Cloth (Premium)", ne: "पोपलिन कपडा (राम्रो)", price: "" },
      { en: "Poplin Cloth (Puja G)", ne: "पोपलिन कपडा (पूजा - G)", price: "" },
      { en: "Flag Cloth", ne: "ध्वजा कपडा", price: "" },
      { en: "Ram-Naam Cotton Towel (Gamcha) (Basic)", ne: "रामनामी गाम्चा (सस्तो)", price: "" },
      { en: "Velvet Banner (EOP)", ne: "भेलबेट ब्यानर (EOP)", price: "" },
      { en: "Sacred Thread 10 No.", ne: "धागो १० नम्बर", price: "" },
      { en: "Sacred Thread 25 No.", ne: "धागो २५ नम्बर", price: "" },
      { en: "Sacred Thread 40 No.", ne: "धागो ४० नम्बर", price: "" },
    ]
  },
  {
    id: "mala",
    en: "Mala & Rudraksha",
    ne: "माला / रुद्राक्ष",
    icon: "📿",
    items: [
      { en: "Rudraksha Prayer Beads (Mala) 108 Beads (NP)", ne: "रुद्राक्ष माला 108 दाना(NP)", price: "" },
      { en: "Rudraksha Prayer Beads (Mala) 108 Beads (IND)", ne: "रुद्राक्ष माला 108 दाना (IND)", price: "" },
      { en: "Prayer Beads (Mala)", ne: "माला", price: "" },
    ]
  },
  {
    id: "consumables",
    en: "Ritual Consumables",
    ne: "पूजा सामग्री (खाद्य/अन्य)",
    icon: "🌾",
    items: [
      { en: "Black Sesame Seeds", ne: "कालो तिल", price: "" },
      { en: "Barley Flour", ne: "जौको पिठो", price: "" },
      { en: "Barley Roasted Flour (Satu)", ne: "जौको सातु", price: "" },
      { en: "Barley", ne: "जौ", price: "" },
      { en: "Ghee Medium", ne: "घिउ मिडियम", price: "" },
      { en: "Ghee Small", ne: "घिउ सानो", price: "" },
      { en: "Dry Coconut", ne: "सुक्खा नरिवल", price: "" },
      { en: "Navagraha Chakra", ne: "nawagraha chakra", price: "" },
      { en: "Nine-Grain Mix (Nauanna)", ne: "nauanna", price: "" },
      { en: "Suhaag / Saubhagya Items", ne: "saubhagye", price: "" },
    ]
  },
  {
    id: "kitchen",
    en: "Kitchen & Household Items",
    ne: "भान्साका सामान",
    icon: "🍳",
    items: [
      { en: "Bronze Puja Mortar (Ankhora)", ne: "कासको पूजा अंखरा", price: "" },
      { en: "Bronze Mortar (Ankhora)", ne: "कासको अंखारा", price: "" },
      { en: "Brass Spoon", ne: "पित्तलको चम्चा", price: "" },
      { en: "Steel Spice Box (Hulas)", ne: "स्टीलको मसलादनी (हुलास)", price: "" },
      { en: "Steel Tiffin Box (Hulas)", ne: "स्टीलको टिफिन (हुलास)", price: "" },
      { en: "Steel Mortar (Ankhora)", ne: "स्टीलको अंखारा", price: "" },
      { en: "Steel Oil Container", ne: "स्टीलको तेलदानी", price: "" },
      { en: "Steel Ladle", ne: "स्टीलको टमी", price: "" },
      { en: "Mortar (Okhli)", ne: "ओखली", price: "" },
      { en: "Ceramic Cup Set", ne: "सेरामिक कप सेट", price: "" },
      { en: "Oil Container", ne: "तेलदानी", price: "" },
      { en: "Thermos", ne: "थर्मस", price: "" },
      { en: "Mixer/Grinder", ne: "मिक्चर", price: "" },
      { en: "Rice Cooker (Large)", ne: "राइश कुकर (ठुलो)", price: "" },
      { en: "Rice Cooker (Small)", ne: "राइश कुकर (सानो)", price: "" },
      { en: "Pressure Cooker", ne: "प्रेसर कुकर", price: "" },
      { en: "Hot Case Steel", ne: "हट केश स्टिल", price: "" },
      { en: "Large Broom", ne: "thulo jhadu", price: "" },
      { en: "Bamboo Broom", ne: "baas jhadu", price: "" },
      { en: "Babiyo Grass Rope", ne: "babiyo dori", price: "" },
    ]
  },
  {
    id: "misc",
    en: "Other Puja Items",
    ne: "अन्य सामग्री",
    icon: "✨",
    items: [
      { en: "Food Stand", ne: "खाना स्टेन्ड", price: "" },
      { en: "Umbrella Deluxe", ne: "छाता महंगो", price: "" },
      { en: "Umbrella Standard", ne: "छाता नर्मल", price: "" },
      { en: "Copper Trident (Trishul)", ne: "तामाको त्रिशूल", price: "" },
      { en: "Copper Engraved Kalash (Pot)", ne: "तामाको बुट्टे कलस", price: "" },
      { en: "Brass Peacock Fan (Playable)", ne: "पित्तलको मजुरा (बजाउने)", price: "" },
      { en: "Horse Horseshoe", ne: "घोडाको नाल", price: "" },
      { en: "Brass Ceiling Ornament", ne: "पित्तलको आसमान", price: "" },
      { en: "Brass Tika Stand", ne: "पित्तलको टिका स्ट्यान्ड", price: "" },
      { en: "White Slippers", ne: "सेतो चप्पल", price: "" },
      { en: "Beaded Stick", ne: "दाने लौरो", price: "" },
      { en: "FOLDING Umbrella (NORMAL)", ne: "FOLDING छाता (NORMAL)", price: "" },
      { en: "Iron Trident (Trishul)", ne: "फलामको त्रिशुल", price: "" },
      { en: "Straw Slippers", ne: "परालको चप्पल", price: "" },
    ]
  },
];
